# coding: utf-8

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'digest/kangarootwelve/version'

Gem::Specification.new do |spec|
  spec.name          = "digest-kangarootwelve"
  spec.version       = Digest::KangarooTwelve::VERSION
  spec.authors       = ["konsolebox"]
  spec.email         = ["konsolebox@gmail.com"]
  spec.summary       = "KangarooTwelve for Ruby"
  spec.description   = "A KangarooTwelve library that works on top of Digest::Base."
  spec.homepage      = "https://github.com/konsolebox/digest-kangarootwelve-ruby"
  spec.license       = "MIT"

  spec.required_ruby_version = '>= 2.2'

  spec.files = %w{
    Gemfile
    LICENSE
    README.md
    Rakefile
    digest-kangarootwelve.gemspec
    ext/digest/kangarootwelve/extconf.rb
    ext/digest/kangarootwelve/utils.h
    ext/digest/kangarootwelve/keccak/armv6m/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/armv6m/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/armv6m/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/armv6m/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/armv6m/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/armv6m/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/armv6m/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/armv6m/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/armv6m/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/armv6m/KeccakP-1600-u2-32bi-armv6m-le-gcc.s
    ext/digest/kangarootwelve/keccak/armv6m/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/armv6m/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/armv6m/ext.link.c
    ext/digest/kangarootwelve/keccak/armv7a/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/armv7a/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/armv7a/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/armv7a/KeccakP-1600-armv7a-le-neon-gcc.s
    ext/digest/kangarootwelve/keccak/armv7a/KeccakP-1600-inplace-pl2-armv7a-neon-le-gcc.s
    ext/digest/kangarootwelve/keccak/armv7a/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/armv7a/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/armv7a/KeccakP-1600-times4-on2.c
    ext/digest/kangarootwelve/keccak/armv7a/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/armv7a/KeccakP-1600-times8-on2.c
    ext/digest/kangarootwelve/keccak/armv7a/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/armv7a/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/armv7a/ext.link.c
    ext/digest/kangarootwelve/keccak/armv7m/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/armv7m/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/armv7m/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/armv7m/KeccakP-1600-inplace-32bi-armv7m-le-gcc.s
    ext/digest/kangarootwelve/keccak/armv7m/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/armv7m/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/armv7m/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/armv7m/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/armv7m/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/armv7m/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/armv7m/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/armv7m/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/armv7m/ext.link.c
    ext/digest/kangarootwelve/keccak/armv8a/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/armv8a/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/armv8a/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/armv8a/KeccakP-1600-armv8a-neon.s
    ext/digest/kangarootwelve/keccak/armv8a/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/armv8a/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/armv8a/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/armv8a/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/armv8a/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/armv8a/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/armv8a/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/armv8a/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/armv8a/ext.link.c
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakP-1600-x86-64-shld-gas.s
    ext/digest/kangarootwelve/keccak/asmx86-64shld/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/asmx86-64shld/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/asmx86-64shld/ext.link.c
    ext/digest/kangarootwelve/keccak/asmx86-64/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakP-1600-x86-64-gas.s
    ext/digest/kangarootwelve/keccak/asmx86-64/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/asmx86-64/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/asmx86-64/ext.link.c
    ext/digest/kangarootwelve/keccak/avr8/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/avr8/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/avr8/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/avr8/KeccakP-1600-avr8-fast.s
    ext/digest/kangarootwelve/keccak/avr8/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/avr8/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/avr8/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/avr8/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/avr8/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/avr8/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/avr8/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/avr8/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/avr8/ext.link.c
    ext/digest/kangarootwelve/keccak/bulldozer/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-XOP.c
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-XOP-config.h
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-times2-SIMD128.c
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-times4-on2.c
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-times8-on2.c
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/bulldozer/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/bulldozer/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/bulldozer/SIMD128-config.h
    ext/digest/kangarootwelve/keccak/bulldozer/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/bulldozer/ext.link.c
    ext/digest/kangarootwelve/keccak/common/KangarooTwelve.c
    ext/digest/kangarootwelve/keccak/common/KangarooTwelve.h
    ext/digest/kangarootwelve/keccak/common/KeccakDuplex.inc
    ext/digest/kangarootwelve/keccak/common/KeccakDuplexWidth1600.c
    ext/digest/kangarootwelve/keccak/common/KeccakDuplexWidth1600.h
    ext/digest/kangarootwelve/keccak/common/KeccakDuplex-common.h
    ext/digest/kangarootwelve/keccak/common/KeccakSponge.inc
    ext/digest/kangarootwelve/keccak/common/KeccakSpongeWidth1600.c
    ext/digest/kangarootwelve/keccak/common/KeccakSpongeWidth1600.h
    ext/digest/kangarootwelve/keccak/common/KeccakSponge-common.h
    ext/digest/kangarootwelve/keccak/common/Phases.h
    ext/digest/kangarootwelve/keccak/common/align.h
    ext/digest/kangarootwelve/keccak/common/brg_endian.h
    ext/digest/kangarootwelve/keccak/compact/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/compact/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-compact64.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/compact/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/compact/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/compact/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/compact/ext.link.c
    ext/digest/kangarootwelve/keccak/generic32lc/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-inplace32BI.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32lc/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/generic32lc/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/generic32lc/ext.link.c
    ext/digest/kangarootwelve/keccak/generic32/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-inplace32BI.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/generic32/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/generic32/ext.link.c
    ext/digest/kangarootwelve/keccak/generic64lc/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-64.macros
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-opt64.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-opt64-config.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic64lc/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/generic64lc/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/generic64lc/ext.link.c
    ext/digest/kangarootwelve/keccak/generic64/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-64.macros
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-opt64.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-opt64-config.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/generic64/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic64/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/generic64/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/generic64/ext.link.c
    ext/digest/kangarootwelve/keccak/haswell/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/haswell/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-AVX2.s
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-times2-SIMD128.c
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-times4-SIMD256.c
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-times8-on4.c
    ext/digest/kangarootwelve/keccak/haswell/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/haswell/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/haswell/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/haswell/SIMD128-config.h
    ext/digest/kangarootwelve/keccak/haswell/SIMD256-config.h
    ext/digest/kangarootwelve/keccak/haswell/ext.link.c
    ext/digest/kangarootwelve/keccak/nehalem/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/nehalem/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-64.macros
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-opt64.c
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-opt64-config.h
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-times2-SIMD128.c
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-times4-on2.c
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-times8-on2.c
    ext/digest/kangarootwelve/keccak/nehalem/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/nehalem/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/nehalem/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/nehalem/SIMD128-config.h
    ext/digest/kangarootwelve/keccak/nehalem/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/nehalem/ext.link.c
    ext/digest/kangarootwelve/keccak/reference32bits/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-reference.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-reference32BI.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/reference32bits/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/reference32bits/displayIntermediateValues.c
    ext/digest/kangarootwelve/keccak/reference32bits/displayIntermediateValues.h
    ext/digest/kangarootwelve/keccak/reference32bits/ext.link.c
    ext/digest/kangarootwelve/keccak/reference/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/reference/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-reference.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-reference.h
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/reference/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/reference/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/reference/displayIntermediateValues.c
    ext/digest/kangarootwelve/keccak/reference/displayIntermediateValues.h
    ext/digest/kangarootwelve/keccak/reference/ext.link.c
    ext/digest/kangarootwelve/keccak/sandybridge/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-64.macros
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-opt64.c
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-opt64-config.h
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-times2-SIMD128.c
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-times4-on2.c
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-times8-on2.c
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/sandybridge/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/sandybridge/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/sandybridge/SIMD128-config.h
    ext/digest/kangarootwelve/keccak/sandybridge/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/sandybridge/ext.link.c
    ext/digest/kangarootwelve/keccak/skylakex/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/skylakex/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-AVX512.c
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-AVX512-config.h
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-times2-SIMD512.c
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-times4-SIMD512.c
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-times8-SIMD512.c
    ext/digest/kangarootwelve/keccak/skylakex/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/skylakex/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/skylakex/SIMD512-2-config.h
    ext/digest/kangarootwelve/keccak/skylakex/SIMD512-4-config.h
    ext/digest/kangarootwelve/keccak/skylakex/SIMD512-config.h
    ext/digest/kangarootwelve/keccak/skylakex/ext.link.c
    ext/digest/kangarootwelve/ext.c
    test/test.rb
  }

  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ["lib"]

  spec.add_development_dependency "rake"
  spec.add_development_dependency "rake-compiler", "~> 1.0"
  spec.add_development_dependency "minitest", "~> 5.8"

  spec.extensions = %w[ext/digest/kangarootwelve/extconf.rb]
end
