# coding: utf-8

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'digest/kangarootwelve/version'

Gem::Specification.new do |spec|
  spec.name          = "digest-kangarootwelve"
  spec.version       = Digest::KangarooTwelve::VERSION
  spec.authors       = ["konsolebox"]
  spec.email         = ["konsolebox@gmail.com"]
  spec.summary       = "KangarooTwelve for Ruby"
  spec.description   = "A KangarooTwelve library that works on top of Digest::Base."
  spec.homepage      = "https://github.com/konsolebox/digest-kangarootwelve-ruby"
  spec.license       = "MIT"

  spec.required_ruby_version = '>= 2.2'

  spec.files = %w{
    Gemfile
    LICENSE
    README.md
    Rakefile
    digest-kangarootwelve.gemspec
    ext/digest/kangarootwelve/extconf.rb
    ext/digest/kangarootwelve/utils.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/generic32lc/ext.link.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/generic32lc/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/generic32lc/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32lc/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32lc/KeccakP-1600-inplace32BI.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-opt64.c
    ext/digest/kangarootwelve/keccak/generic64lc/ext.link.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-64.macros
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-opt64-config.h
    ext/digest/kangarootwelve/keccak/generic64lc/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/generic64lc/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic64lc/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/generic64lc/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/compact/ext.link.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-compact64.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/compact/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/compact/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/compact/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/compact/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/compact/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/compact/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/Haswell/SIMD256-config.h
    ext/digest/kangarootwelve/keccak/Haswell/ext.link.c
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-times8-on4.c
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/Haswell/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-times4-SIMD256.c
    ext/digest/kangarootwelve/keccak/Haswell/SIMD128-config.h
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-times2-SIMD128.c
    ext/digest/kangarootwelve/keccak/Haswell/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-AVX2.s
    ext/digest/kangarootwelve/keccak/Haswell/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/Haswell/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/Haswell/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/ARMv7M/ext.link.c
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv7M/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/ARMv7M/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakP-1600-inplace-32bi-armv7m-le-gcc.s
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv7M/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-opt64.c
    ext/digest/kangarootwelve/keccak/SandyBridge/ext.link.c
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-64.macros
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-opt64-config.h
    ext/digest/kangarootwelve/keccak/SandyBridge/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/SandyBridge/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/SandyBridge/SIMD128-config.h
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-times8-on2.c
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-times2-SIMD128.c
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/SandyBridge/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/SandyBridge/KeccakP-1600-times4-on2.c
    ext/digest/kangarootwelve/keccak/common/KeccakDuplex.inc
    ext/digest/kangarootwelve/keccak/common/KangarooTwelve.h
    ext/digest/kangarootwelve/keccak/common/Phases.h
    ext/digest/kangarootwelve/keccak/common/KeccakSponge-common.h
    ext/digest/kangarootwelve/keccak/common/brg_endian.h
    ext/digest/kangarootwelve/keccak/common/KeccakSpongeWidth1600.h
    ext/digest/kangarootwelve/keccak/common/KeccakDuplex-common.h
    ext/digest/kangarootwelve/keccak/common/KeccakSponge.inc
    ext/digest/kangarootwelve/keccak/common/KeccakDuplexWidth1600.c
    ext/digest/kangarootwelve/keccak/common/KeccakDuplexWidth1600.h
    ext/digest/kangarootwelve/keccak/common/align.h
    ext/digest/kangarootwelve/keccak/common/KeccakSpongeWidth1600.c
    ext/digest/kangarootwelve/keccak/common/KangarooTwelve.c
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/asmX86-64/ext.link.c
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakP-1600-x86-64-gas.s
    ext/digest/kangarootwelve/keccak/asmX86-64/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/asmX86-64/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/asmX86-64/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/reference/ext.link.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/reference/displayIntermediateValues.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-reference.c
    ext/digest/kangarootwelve/keccak/reference/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-reference.h
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/reference/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/reference/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/reference/displayIntermediateValues.h
    ext/digest/kangarootwelve/keccak/reference/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/reference/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/SkylakeX/ext.link.c
    ext/digest/kangarootwelve/keccak/SkylakeX/SIMD512-config.h
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-times2-SIMD512.c
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-times8-SIMD512.c
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-times4-SIMD512.c
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/SkylakeX/SIMD512-2-config.h
    ext/digest/kangarootwelve/keccak/SkylakeX/SIMD512-4-config.h
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-AVX512.c
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/SkylakeX/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-AVX512-config.h
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/SkylakeX/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/ARMv8A/ext.link.c
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv8A/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakP-1600-armv8a-neon.s
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/ARMv8A/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv8A/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-opt64.c
    ext/digest/kangarootwelve/keccak/generic64/ext.link.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-64.macros
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-opt64-config.h
    ext/digest/kangarootwelve/keccak/generic64/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/generic64/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic64/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/generic64/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/generic64/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/Bulldozer/ext.link.c
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/Bulldozer/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/Bulldozer/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-XOP-config.h
    ext/digest/kangarootwelve/keccak/Bulldozer/SIMD128-config.h
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-times8-on2.c
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-XOP.c
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-times2-SIMD128.c
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/Bulldozer/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/Bulldozer/KeccakP-1600-times4-on2.c
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/asmX86-64shld/ext.link.c
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/asmX86-64shld/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakP-1600-x86-64-shld-gas.s
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/asmX86-64shld/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-opt64.c
    ext/digest/kangarootwelve/keccak/Nehalem/ext.link.c
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-unrolling.macros
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-64.macros
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-opt64-config.h
    ext/digest/kangarootwelve/keccak/Nehalem/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/Nehalem/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/Nehalem/SIMD128-config.h
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-times8-on2.c
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-times2-SIMD128.c
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/Nehalem/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/Nehalem/KeccakP-1600-times4-on2.c
    ext/digest/kangarootwelve/keccak/ARMv7A/ext.link.c
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv7A/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakP-1600-times8-on2.c
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakP-1600-armv7a-le-neon-gcc.s
    ext/digest/kangarootwelve/keccak/ARMv7A/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakP-1600-inplace-pl2-armv7a-neon-le-gcc.s
    ext/digest/kangarootwelve/keccak/ARMv7A/KeccakP-1600-times4-on2.c
    ext/digest/kangarootwelve/keccak/AVR8/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/AVR8/ext.link.c
    ext/digest/kangarootwelve/keccak/AVR8/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/AVR8/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/AVR8/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/AVR8/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/AVR8/KeccakP-1600-avr8-fast.s
    ext/digest/kangarootwelve/keccak/AVR8/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/AVR8/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/AVR8/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/AVR8/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/AVR8/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/AVR8/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/generic32/ext.link.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/generic32/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/generic32/SnP-Relaned.h
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/generic32/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/generic32/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/generic32/KeccakP-1600-inplace32BI.c
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakP-1600-u2-32bi-armv6m-le-gcc.s
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/ARMv6M/ext.link.c
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv6M/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/ARMv6M/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/ARMv6M/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times8-on1.c
    ext/digest/kangarootwelve/keccak/reference32bits/ext.link.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-SnP.h
    ext/digest/kangarootwelve/keccak/reference32bits/displayIntermediateValues.c
    ext/digest/kangarootwelve/keccak/reference32bits/PlSnP-Fallback.inc
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times2-on1.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times8-SnP.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-reference.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-reference32BI.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times4-SnP.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakSpongeWidth1600.link.c
    ext/digest/kangarootwelve/keccak/reference32bits/KangarooTwelve.link.c
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times4-on1.c
    ext/digest/kangarootwelve/keccak/reference32bits/displayIntermediateValues.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakP-1600-times2-SnP.h
    ext/digest/kangarootwelve/keccak/reference32bits/KeccakDuplexWidth1600.link.c
    ext/digest/kangarootwelve/ext.c
    test/test.rb
  }

  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ["lib"]

  spec.add_development_dependency "rake"
  spec.add_development_dependency "rake-compiler", "~> 1.0"
  spec.add_development_dependency "minitest", "~> 5.8"

  spec.extensions = %w[ext/digest/kangarootwelve/extconf.rb]
end
